In [ ]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [15]:
import torch
import torch.nn as nn

In [ ]:
rng = np.random.default_rng(seed=42) 
Q = rng.random(size=(4, 8))
K = rng.random(size=(4, 8))
V = rng.random(size=(4, 8))

8

In [ ]:
import torch
import torch.nn as nn


X = torch.rand(2, 4, 8)

attention = SelfAttention(d_model=8)
output, attention_weights = attention(X)

print("X:", X.shape)
print("Output:", output.shape)
print("Attention:", attention_weights.shape)
print("Row sums:", attention_weights.sum(dim=-1))


TypeError: SelfAttention.__init__() missing 1 required positional argument: 'num_heads'

In [63]:
X = torch.rand(2, 4, 8)

attention = SelfAttention(
    d_model=8,
    num_heads=2
)

output, attention_weights = attention(X)

print("X:", X.shape)
print("Output:", output.shape)
print("Attention:", attention_weights.shape)
print("Row sums:", attention_weights.sum(dim=-1))
X.shape == (2,4,8)

X: torch.Size([2, 4, 8])
Output: torch.Size([2, 4, 8])
Attention: torch.Size([2, 2, 4, 4])
Row sums: tensor([[[1.0000, 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000]],

        [[1.0000, 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000]]], grad_fn=<SumBackward1>)


True

In [99]:
L = 4
D = 8
position = torch.arange(L, dtype=torch.float32).unsqueeze(1)

even_dims = torch.arange(0,D,2, dtype=torch.float32)

denominator = 10000 ** (even_dims / D)

angles = position / denominator


PE = torch.zeros(L, D)
position = torch.arange(L, dtype=torch.float32).unsqueeze(1)
denominator = 10000 ** (even_dims / D)
angles = position / denominator

PE[:, 0::2] = torch.sin(angles)
PE[:, 1::2] = torch.cos(angles)
PE

tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          1.0000e+00,  0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  5.4030e-01,  9.9833e-02,  9.9500e-01,  9.9998e-03,
          9.9995e-01,  1.0000e-03,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  1.9867e-01,  9.8007e-01,  1.9999e-02,
          9.9980e-01,  2.0000e-03,  1.0000e+00],
        [ 1.4112e-01, -9.8999e-01,  2.9552e-01,  9.5534e-01,  2.9995e-02,
          9.9955e-01,  3.0000e-03,  1.0000e+00]])

In [54]:
from numpy import float32
X = torch.zeros(2, 4, 8)
known_encodings = torch.tensor([0,1,0,1,0,1,0,1], dtype=torch.float32)
pos_encoding = PositionalEncoding(d_model=8, max_len=10)
result = pos_encoding(X)
print(result[0,0,:])
print(known_encodings)
assert torch.allclose(result[0,0,:], known_encodings)


tensor([0., 1., 0., 1., 0., 1., 0., 1.])
tensor([0., 1., 0., 1., 0., 1., 0., 1.])
